#!/usr/bin/env python3
import logging, pprint
from colorlog import ColoredFormatter

formatter = ColoredFormatter(
        "%(log_color)s%(levelname)-8s%(reset)s %(message)s",
        datefmt=None,
        reset=True,
        log_colors={
                'DEBUG':    'cyan',
                'INFO':     'green',
                'WARNING':  'yellow',
                'ERROR':    'red',
                'CRITICAL': 'red,bg_white',
        },
        secondary_log_colors={},
        style='%'
)

# create console handler and set level to debug
ch = logging.StreamHandler()
ch.setLevel(logging.NOTSET)

# add formatter to ch
ch.setFormatter(formatter)

logging.basicConfig(level=logging.DEBUG, handlers=[ch])

l = logging.getLogger('guy')

l.debug('guy')
l.info('guy')
l.warning('guy')
l.error('guy')
l.critical('guy')
